### ISSUE TITLE
www.nexusmods.com

### ISSUE THREAD

**Issue by kevindevm** [Sainan/Universal-Bypass#1639] opened 2020-11-16 22:13 UTC
not working for "mod manager download" 

![02582](https://user-images.githubusercontent.com/7692819/99314358-c1898d00-283f-11eb-88b5-f2da4a1dacd0.gif)

**Comment by respecting** [comment] 2020-11-17 02:00
Dupe of #1253

**Closed** 2020-11-17 08:45 UTC
