### ISSUE TITLE
New Site for Universal Bypass

### ISSUE THREAD

**Issue by ELEduDeLaGente** [Sainan/Universal-Bypass#1861] opened 2021-03-17 14:42 UTC
https://fc.lc/

Sorry for the inconvenience and I hope that it is useful that you now know this site

**Comment by Sainan** [comment] 2021-03-17 14:56
Example link?

**Comment by ELEduDeLaGente** [comment] 2021-03-17 15:07
https://fc.lc/Kxy2g3

**Comment by Sainan** [comment] 2021-03-17 22:50
Duplicate of #1841

**Closed by Sainan** 2021-03-17 22:50 UTC
Labels: awaiting response

**Comment by ELEduDeLaGente** [comment] 2021-03-18 03:51
Ahh? Sorry I'm so dummy, but i don't understand
