### ISSUE TITLE
Change the look of google

### ISSUE THREAD

**Issue by Kimitaku** [Sainan/Universal-Bypass#1706] opened 2021-01-11 01:40 UTC
Before it gave me no problem, today I went to google and a google something different than usual appeared and with a black line, when deactivating universal bypass that weird google no longer appears. Note: (I am Spanish, I used the translator)
Image: https://imgur.com/a/ftDgCad

**Comment by ahfidbilal** [comment] 2021-01-11 01:41
Also, blocked from Cloudflare


"Sorry, you have been blocked
You are unable to access"

**Comment by sitiom** [comment] 2021-01-11 01:44
Duplicate of #1704

**Closed** 2021-01-11 03:07 UTC
Labels: broken bypass
