### ISSUE TITLE
https://douploads.net/pidblc2q4ryo skipped countdown

### ISSUE THREAD

**Issue by Uranite** [Sainan/Universal-Bypass#1881] opened 2021-03-29 16:44 UTC
![image](https://user-images.githubusercontent.com/62639703/112870646-9f0a5900-90e8-11eb-8bd1-3d329a85a1bb.png)
https://douploads.net/pidblc2q4ryo

**Comment by Sainan** [comment] 2021-03-29 18:34
Duplicate of #1872

**Closed by Sainan** 2021-03-29 18:34 UTC
Labels: bypass detected
