### ISSUE TITLE
[Request/Bug?-CB?] apk.miuiku.com

### ISSUE THREAD

**Issue by Cyberavater** [Sainan/Universal-Bypass#1318] opened 2020-06-18 08:53 UTC
Example Link: https://bit.ly/2F9DSOE

**Comment by Cyberavater** [comment] 2020-06-18 08:57
You'll need to click "Click here to continue" 2 or 3 times.

**Comment by exodius48** [comment] 2020-07-31 06:00
New link: `https://apk.miuiku.com/p2cHKf7Ud9`

**Comment by Sainan** [comment] 2020-07-31 12:26
Duplicate of #1177

**Closed by Sainan** 2020-07-31 12:26 UTC
Labels: new bypass
