### ISSUE TITLE
https://lnk.news

### ISSUE THREAD

**Issue by Haru234** [Sainan/Universal-Bypass#1467] opened 2020-08-25 12:54 UTC
Hello, this extension is amazing and it has saved me tons of time, thanks!!

When I click on the site, bypass not working and the site constantly reloads itself
 
https://lnk.news

https://lnk.news/2rOd8

**Comment by DineshSolanki** [comment] 2020-08-29 09:56
***for code contributors*** - I have inspected the page and the first page contains a button with id -"csubmit" that opens up a captcha before submitting the form(id=display_go_form).
then there's another button(id=get_link_btn) which leads to destination.
the target of first and second button is - https://lnk.news/go/2rOd8, https://lnk.news/links/skip/2rOd8

and I have seen this pattern in another adshortner but can't remember the name. Maybe this comment will save some time.

**Comment by DineshSolanki** [comment] 2020-08-29 10:01
Duplicate of #1464

**Closed** 2020-08-29 22:17 UTC
Labels: new bypass
