### ISSUE TITLE
Universal Bypass breaks google and when going to reddit it says im a bot

### ISSUE THREAD

**Issue by Shinzef** [Sainan/Universal-Bypass#1707] opened 2021-01-11 01:48 UTC
![image](https://user-images.githubusercontent.com/72062931/104141486-0cfc8980-53f2-11eb-8be0-80bf8f295e5a.png)

with bypass

![image](https://user-images.githubusercontent.com/72062931/104141493-18e84b80-53f2-11eb-8ae5-dfb56b44e1d9.png)

with bypass

![image](https://user-images.githubusercontent.com/72062931/104141505-24d40d80-53f2-11eb-81ed-8fa4884464c4.png)

without bypass

![image](https://user-images.githubusercontent.com/72062931/104141513-2d2c4880-53f2-11eb-9e50-8322ef872225.png)

errors in the extension page

**Comment by OothecaPickle** [comment] 2021-01-11 01:55
same

**Comment by avileena** [comment] 2021-01-11 01:55
same here disabling it fixes the problem

**Comment by fsproede** [comment] 2021-01-11 01:58
It changes the HTTP_USER_AGENT to "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"

**Comment by Sarpar12** [comment] 2021-01-11 01:59
Same Issue here. Latest edge version

**Comment by kainjinez** [comment] 2021-01-11 02:03
Duplicate of #1704

**Closed** 2021-01-11 03:07 UTC
